### ISSUE TITLE
Health indicator appears to leak connections when another health indicator is down

### ISSUE THREAD

**Issue by zdegner** [micronaut-projects/micronaut-redis#150] opened 2021-01-06 20:50 UTC
We've noticed that Redis connections will slowly but consistently leak over time if another health indicator is down. The application will eventually exhaust the connections up to the limit on the Redis server.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Micronaut application with the Redis Lettuce module 
2. Add a failing health indicator
3. Run the application in Kubernetes with a readiness probe in place 
4. Monitor the connections in redis over about 30-60 minutes (can use "> client list" command)

### Expected Behaviour

Connections should remain relatively stable over time.

### Actual Behaviour

Connections slowly increase over time until the connection limit in Redis is eventually hit. 
I'm seeing about 50 connections per hour created when running locally.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.2.2
- **JDK Version:** 11

### Example Application

https://github.com/zdegner/micronaut-redis-health-indicator-connection-leak

**Comment by treezio** [comment] 2021-02-23 09:55
We are experiencing the same issue.

**Comment by racevedoo** [comment] 2021-03-09 10:35
I was able to reproduce this. In my tests, a new "leaked" connection appears every 1min in the `client list` response. I did some digging but couldn't find the reason. I'll keep investigating.

**Comment by racevedoo** [comment] 2021-03-10 00:29
Apparently, the redis connection opened by `RedisHealthIndicator` is not closed if the failing health indicator throws the exception before the redis indicator can release the connection. Here are some logs:

For the leaked connection:
```
io.lettuce.core.RedisClient - Trying to get a Redis connection for: redis://172.17.0.3?clientName=application
i.m.m.health.indicator.HealthResult - Health indicator [always-fails] reported exception: java.lang.IllegalStateException: Expect this indicator to fail
java.lang.IllegalStateException: Expect this indicator to fail
	at com.example.ClientCredentialsTokenIndicator.getHealthInformation(ClientCredentialsTokenIndicator.java:24)
	at com.example.ClientCredentialsTokenIndicator.getHealthInformation(ClientCredentialsTokenIndicator.java:11)
	at io.micronaut.management.health.indicator.AbstractHealthIndicator.getHealthResult(AbstractHealthIndicator.java:72)
	at io.micronaut.core.async.publisher.AsyncSingleResultPublisher$ExecutorServiceSubscription.lambda$request$1(AsyncSingleResultPublisher.java:100)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
io.lettuce.core.RedisClient - Resolved SocketAddress 172.17.0.3:6379 using redis://172.17.0.3?clientName=application
io.lettuce.core.AbstractRedisClient - Connecting to Redis at 172.17.0.3:6379
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, [id: 0x5ed4c52c] (inactive), chid=0x19] channelRegistered()
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] write(ctx, AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
i.l.core.protocol.CommandEncoder - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379] writing command AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Received: 89 bytes, 1 commands in the stack
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Stack contains: 1 commands
i.l.core.protocol.RedisStateMachine - Decode done, empty stack: true
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Completing command AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='ERR unknown command `HELLO`, with args beginning with: `3`, `SETNAME`, `application`, '], commandType=io.lettuce.core.protocol.Command]
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] write(ctx, AsyncCommand [type=PING, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
i.l.core.protocol.CommandEncoder - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379] writing command AsyncCommand [type=PING, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Received: 7 bytes, 1 commands in the stack
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Stack contains: 1 commands
i.l.core.protocol.RedisStateMachine - Decode done, empty stack: true
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Completing command AsyncCommand [type=PING, output=StatusOutput [output=PONG, error='null'], commandType=io.lettuce.core.protocol.Command]
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] write(ctx, [AsyncCommand [type=CLIENT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]], promise)
i.l.core.protocol.CommandEncoder - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379] writing command AsyncCommand [type=CLIENT, output=StatusOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Received: 5 bytes, 1 commands in the stack
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Stack contains: 1 commands
i.l.core.protocol.RedisStateMachine - Decode done, empty stack: true
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] Completing command AsyncCommand [type=CLIENT, output=StatusOutput [output=OK, error='null'], commandType=io.lettuce.core.protocol.Command]
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] channelActive()
i.l.core.protocol.DefaultEndpoint - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, epid=0x19] activateEndpointAndExecuteBufferedCommands 0 command(s) buffered
i.l.core.protocol.DefaultEndpoint - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, epid=0x19] activating endpoint
i.l.core.protocol.DefaultEndpoint - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, epid=0x19] flushCommands()
i.l.core.protocol.DefaultEndpoint - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, epid=0x19] flushCommands() Flushing 0 commands
i.l.core.protocol.ConnectionWatchdog - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, last known addr=/172.17.0.3:6379] channelActive()
i.l.core.protocol.CommandHandler - [channel=0xec9e4604, /172.17.0.5:56728 -> /172.17.0.3:6379, chid=0x19] channelActive() done
```

In a "normal" connection, after the `channelActive() done` log, the following line returns:
```
connection = getConnection.apply(client.getBean());
```

However, in a leaked connection the rest of the code in the `getResult` method never returns, so the `connection.close()` is never called.

I see a few solutions:
- Try to understand why the rest of the code is not executed (this is probably related to rxjava)
- Implement the indicator extending `AbstractHealthIndicator` and avoid rxjava usage (so we can close connections properly) - we still need to validate if this fixes the issue

As I'm not deeply familiar with rxjava, my choice would be to extend `AbstractHealthIndicator`

WDYT? @pgressa @ilopmar

**Comment by pgressa** [comment] 2021-03-10 09:25
@racevedoo thanks for investigating that stuff, I'll try to look at it later this week or next week for sure!

**Comment by pgressa** [comment] 2021-03-17 18:02
I have been chasing this bug today. If the health endpoint is triggered by external event, then the connection is closed as expected.

The leaked connections are happening when the [HealthMonitorTask](https://github.com/micronaut-projects/micronaut-core/blob/2.4.x/management/src/main/java/io/micronaut/management/health/monitor/HealthMonitorTask.java) is executed. That's why @racevedoo saw every minute one more leaked connection. The root cause lays in the snippet from HealthMonitorTask below:
```
List<Publisher<HealthResult>> healthResults = healthIndicators
            .stream()
            .map(HealthIndicator::getResult)
            .collect(Collectors.toList());

        Flowable<HealthResult> resultFlowable = Flowable
            .merge(healthResults)
            .filter(healthResult -> {
                    HealthStatus status = healthResult.getStatus();
                    return status.equals(HealthStatus.DOWN) || !status.getOperational().orElse(true);
                }
            );

        resultFlowable.firstElement().subscribe(new MaybeObserver<HealthResult>() {
...
```

We work with flowables, which are asynchronously executed, so basically this line `resultFlowable.firstElement()` causes that the first failing health result (which in our case is the artificially failing one as it's executed super fast) is processed as first and the whole flowable machinery is then cancelled. Among this not finished indicators is the RedisHealthIndicator with the  code snippet below:
```
  return redisClients.flatMap(client -> {
            R connection;
            String connectionName = client.getIdentifier().getName();
            String dbName = "redis(" + connectionName + ")";
            try {
                connection = getConnection.apply(client.getBean());
            } catch (Exception e) {
                HealthResult result = HealthResult
                        .builder(dbName, HealthStatus.DOWN)
                        .exception(e)
                        .build();
                return Flux.just(result);
            }

            Mono<String> pingCommand = getReactive.apply(connection).ping();
            pingCommand = pingCommand.timeout(Duration.ofSeconds(TIMEOUT_SECONDS)).retry(RETRY);
            return pingCommand.map(s -> {
                try {
                    if (s.equalsIgnoreCase("pong")) {
                        return HealthResult
                                .builder(dbName, HealthStatus.UP)
                                .build();
                    }
                    return HealthResult
                            .builder(dbName, HealthStatus.DOWN)
                            .details(Collections.singletonMap("message", "Unexpected response: " + s))
                            .build();
                } finally {
                    try {
                        connection.close();
                      // THIS IS NEVER EXECUTED SO THE CONNECTION REMAINS OPEN
                    } catch (Exception e) {
                        // ignore
                    }
                }```

The connection is closed only on error or on success, but not on cancel.

**Closed** 2021-03-19 10:32 UTC
Labels: info: good first issue, priority: high, status: example attached, status: in progress, status: pr submitted, type: bug

**Comment by sdelamo** [comment] 2021-03-23 09:55
@zdegner thanks for reporting. [Micronaut redis 4.0.1](https://github.com/micronaut-projects/micronaut-redis/releases/tag/v4.0.1) should contain a fix for this issue.

**Comment by zdegner** [comment] 2021-03-25 13:50
Excellent, thanks for looking into this!
